package storage;

import java.util.concurrent.ConcurrentHashMap;

/**
 * Class that contains the URL's count generated by Storm cluster.
 * This map automatically handle the concurrency.
 * 
 * This class follows the Singleton pattern. 
 * 
 * @author Gabriele de Capoa
 *
 */

public class URLMap {

	private static ConcurrentHashMap<String, Integer> instance;
	
	/**
	 * Lazy initialization
	 */
	
	public static synchronized ConcurrentHashMap<String, Integer> getInstance(){
		if (instance==null)
			instance = new ConcurrentHashMap<String, Integer>();
		return instance;
	}
	
}
