package storage;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Class that contains the URL's count generated by Storm cluster.
 * This map automatically handles the concurrency.
 * 
 * This class follows the Singleton pattern. 
 * 
 * @author Gabriele de Capoa
 *
 */

public class URLMap {

	private static ConcurrentHashMap<String, Map<String, Integer>> instance;
	
	/**
	 * Lazy initialization
	 */
	
	public static synchronized ConcurrentHashMap<String, Map<String, Integer>> getInstance(){
		if (instance==null)
			instance = new ConcurrentHashMap<String, Map<String, Integer>>();
		return instance;
	}
	
}
