package storage;

import java.util.Map;
import java.util.concurrent.ConcurrentSkipListMap;

/**
 * Class that contains the URL's count generated by Storm cluster.
 * This map automatically handles the concurrency.
 * 
 * This class follows the Singleton pattern. 
 * 
 * @author Gabriele de Capoa, Daniele Morgantini
 *
 */

public class URLMap {

	private static ConcurrentSkipListMap<String, Map<String, Integer>> instance;
	
	/**
	 * Lazy initialization
	 */
	
	public static synchronized ConcurrentSkipListMap<String, Map<String, Integer>> getInstance(){
		if (instance==null)
			instance = new ConcurrentSkipListMap<String, Map<String, Integer>>(); 
		return instance;
	}
	
}
